---
- name: install / uninstall
  hosts: all
  vars:
   - a: tomcat9
   - b: present
   - c: yes
   - d: no
   - e: absent
   - f: purge
  tasks:
   - name: install
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...

