---
- name: to install tomcat,copy,replace,restart and to check url response
  hosts: all
  tasks:
   - name: to install tomcat9
     apt:
      name: tomcat9
      state: present
      update_cache: yes
   - name: to copy
     copy:
      content: "hello"
      dest: /etc/tomcat9/tomcat-users.xml
   - name: to replace
     replace:
      regexp: 8080
      replace: 6060
      dest: /etc/tomcat9/server.xml
   - name: to restart
     service:
      name: tomcat9
      state: restarted
   - name: to check url response
     uri:
      url: http://3.86.42.79:6060
      status_code: 200
...
